module.exports = {
  rules: {
    'max-line-length': [true, 120],
    'variable-name': false,
    'no-increment-decrement': false,
    'no-constant-condition': true,
    'ter-arrow-parens': false,
    'no-magic-numbers': false,
    'prefer-array-literal': false,
    'no-unused-variable': [true],
    'interface-over-type-literal': false,
    'linebreak-style': false,
    'no-var-requires': false,
    'object-literal-sort-keys': false,
    'no-console': [true, 'warn'],
    'ter-indent': [false, 'tab'],
    'jsx-no-multiline-js': [false],
    'jsx-no-lambda': [false],
    'ter-max-len': [true, 120],
    'ter-no-tabs': false,
    'ter-padded-blocks': [true, { classes: 'never' }],
    semicolon: [true, 'always', 'ignore-bound-class-methods'],
    quotemark: [true, 'single'],
  },
};
